clinica/urls.py
from django.contrib import admin
from django.urls import path, include

from main_app import urls as main_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include(main_urls)),
]

main_app/urls.py
from django.urls import path

from . import views

app_name = 'main_app'
urlpatterns = [
    path('', views.index, name='index'),
]

main_app/models.py
from django.db import models

# Create your models here.

main_app/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def index(request):
    return render(request, 'main_app/index.html')

main_app/templates/main_app/base.html
{% extends "base.html" %}

templates/_aside.html
{% load static from staticfiles %}
{% load activeurl %}

<aside class="sidebar">
    <div class="sidebar-container">
        <div class="sidebar-header">
            <div class="brand">
                <img height="40" src="{% static 'img/logo_iq96r.png' %}"> Clinica
            </div>
        </div>
        <nav class="menu">
            {% activeurl css_class="active open" %}
                <ul class="sidebar-menu metismenu" id="sidebar-menu">
                    <li>
                        <a href="{% url 'main_app:index' %}">
                            <i class="fa fa-home"></i> Inicio </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-cube"></i> Administracion
                            <i class="fa arrow"></i>
                        </a>
                        <ul class="sidebar-nav">
                            <li>
                                <a href="#"> Citas </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-bar-chart"></i> Agile Metrics
                            <span class="label label-screenful">by Screenful</span>
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/modularcode/modular-admin-html">
                            <i class="fa fa-github-alt"></i> Theme Docs </a>
                    </li>
                </ul>
            {% endactiveurl %}
        </nav>
    </div>
    <footer class="sidebar-footer">
        <ul class="sidebar-menu metismenu" id="customize-menu">
            <li>
                <ul>
                    <li class="customize">
                        <div class="customize-item">
                            <div class="row customize-header">
                                <div class="col-4"> </div>
                                <div class="col-4">
                                    <label class="title">fixed</label>
                                </div>
                                <div class="col-4">
                                    <label class="title">static</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-4">
                                    <label class="title">Sidebar:</label>
                                </div>
                                <div class="col-4">
                                    <label>
                                        <input class="radio" type="radio" name="sidebarPosition" value="sidebar-fixed">
                                        <span></span>
                                    </label>
                                </div>
                                <div class="col-4">
                                    <label>
                                        <input class="radio" type="radio" name="sidebarPosition" value="">
                                        <span></span>
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-4">
                                    <label class="title">Header:</label>
                                </div>
                                <div class="col-4">
                                    <label>
                                        <input class="radio" type="radio" name="headerPosition" value="header-fixed">
                                        <span></span>
                                    </label>
                                </div>
                                <div class="col-4">
                                    <label>
                                        <input class="radio" type="radio" name="headerPosition" value="">
                                        <span></span>
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-4">
                                    <label class="title">Footer:</label>
                                </div>
                                <div class="col-4">
                                    <label>
                                        <input class="radio" type="radio" name="footerPosition" value="footer-fixed">
                                        <span></span>
                                    </label>
                                </div>
                                <div class="col-4">
                                    <label>
                                        <input class="radio" type="radio" name="footerPosition" value="">
                                        <span></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="customize-item">
                            <ul class="customize-colors">
                                <li>
                                    <span class="color-item color-red" data-theme="red"></span>
                                </li>
                                <li>
                                    <span class="color-item color-orange" data-theme="orange"></span>
                                </li>
                                <li>
                                    <span class="color-item color-green active" data-theme=""></span>
                                </li>
                                <li>
                                    <span class="color-item color-seagreen" data-theme="seagreen"></span>
                                </li>
                                <li>
                                    <span class="color-item color-blue" data-theme="blue"></span>
                                </li>
                                <li>
                                    <span class="color-item color-purple" data-theme="purple"></span>
                                </li>
                                <li>
                                    <span class="color-item color-custom" data-theme="custom"></span>
                                </li>
                            </ul>
                        </div>
                    </li>
                </ul>
                <a href="">
                    <i class="fa fa-cog"></i>
                    Personalizar
                </a>
            </li>
        </ul>
    </footer>
</aside>

templates/_navbar.html
{% load static from staticfiles %}
{% load avatar_tags %}
{% load i18n %}

<header class="header">
    <div class="header-block header-block-collapse d-lg-none d-xl-none">
        <button class="collapse-btn" id="sidebar-collapse-btn">
            <i class="fa fa-bars"></i>
        </button>
    </div>
    <div class="header-block header-block-buttons">
    </div>
    <div class="header-block header-block-nav">
        <ul class="nav-profile">
            <li class="notifications new">
                <a href="" data-toggle="dropdown">
                    <i class="fa fa-bell-o"></i>
                    <sup>
                        <span class="counter">8</span>
                    </sup>
                </a>
                <div class="dropdown-menu notifications-dropdown-menu">
                    <ul class="notifications-container">
                        <li>
                            <a href="" class="notification-item">
                                <div class="img-col">
                                    <div class="img" style="background-image: url('{% static 'img/logo_iq96.png' %}')"></div>
                                </div>
                                <div class="body-col">
                                    <p>
                                        <span class="accent">Zack Alien</span> publico una nueva confirmacion:
                                        <span class="accent">Fix page load performance issue</span>. </p>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="" class="notification-item">
                                <div class="img-col">
                                    <div class="img" style="background-image: url('{% static 'img/logo_iq96.png' %}')"></div>
                                </div>
                                <div class="body-col">
                                    <p>
                                        <span class="accent">Amaya Hatsumi</span> empezo una nueva tarea:
                                        <span class="accent">Dashboard UI design.</span>. </p>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="" class="notification-item">
                                <div class="img-col">
                                    <div class="img" style="background-image: url('{% static 'img/logo_iq96.png' %}')"></div>
                                </div>
                                <div class="body-col">
                                    <p>
                                        <span class="accent">Andy Nouman</span> desplego una nueva version de
                                        <span class="accent">NodeJS REST Api V3</span>
                                    </p>
                                </div>
                            </a>
                        </li>
                    </ul>
                    <footer>
                        <ul>
                            <li>
                                <a href=""> Ver todas </a>
                            </li>
                        </ul>
                    </footer>
                </div>
            </li>
            <li class="profile dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    <div class="img" style="background-image: url('{% avatar_url user 35 %}')"> </div>
                    <span class="name"> {{ user.username }} </span>
                </a>
                <div class="dropdown-menu profile-dropdown-menu" aria-labelledby="dropdownMenu1">
                    <a class="dropdown-item" href="#">
                        <i class="fa fa-user icon"></i> Perfil </a>
                    <a class="dropdown-item" href="#">
                        <i class="fa fa-bell icon"></i> Notificaciones </a>
                    <a class="dropdown-item" href="#">
                        <i class="fa fa-gear icon"></i> Ajustes </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account_logout' %}">
                        <i class="fa fa-power-off icon"></i> Salir
                    </a>
                </div>
            </li>
        </ul>
    </div>
</header>

templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>IQ' ERP | {% block head_title %} Bienvendio {% endblock %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
    <link href="{% static 'css/vendor.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/app-custom.css' %}" id="theme-style" rel="stylesheet" type="text/css">
    <link href="{% static 'toastr/build/toastr.min.css' %}" rel="stylesheet" type="text/css">

    <script>
        var themeSettings = (localStorage.getItem('themeSettings')) ? JSON.parse(localStorage.getItem('themeSettings')) :
            {};
        var themeName = themeSettings.themeName || '';
        if (themeName)
        {
            document.write('<link rel="stylesheet" id="theme-style" href="/static/css/app-' + themeName + '.css">');
        }
        else
        {
            document.write('<link rel="stylesheet" id="theme-style" href="{% static 'css/app-custom.css' %}">');
        }
    </script>

    {% block styles %}
    {% endblock styles %}
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block head_scripts %}
    {% endblock head_scripts %}
</head>
<body>
<!-- begin:: Page -->
<div class="main-wrapper">
    <div class="app" id="app">
        <!-- BEGIN: Header -->
        {% include '_navbar.html' %}
        <!-- END: Header -->
        <!-- BEGIN: Aside -->
        {% include '_aside.html' %}
        <!-- END: Aside -->
        <!-- Begin: Body -->
        <div class="sidebar-overlay" id="sidebar-overlay"></div>
        <div class="sidebar-mobile-menu-handle" id="sidebar-mobile-menu-handle"></div>
        <div class="mobile-menu-handle"></div>
        <article class="content">
            {% block title_block %}
            {% endblock %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><i class="fa fa-times"></i></button>
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock %}
        </article>
        <!-- END: Body -->
        <!-- begin::Footer -->
        <footer class="footer">
            <div class="footer-block author">
                <ul>
                    <li> {% now "Y" %} &copy; IQ' ERP desarrollado por
                        <a href="http://www.iqsd.co" target="_blank">
                            IQ' Software Development
                        </a>
                    </li>
                </ul>
            </div>
        </footer>
        <!-- end::Footer -->
    </div>
</div>
<!-- end:: Page -->

<div class="ref" id="ref">
    <div class="color-primary"></div>
    <div class="chart">
        <div class="color-primary"></div>
        <div class="color-secondary"></div>
    </div>
</div>

<!--begin::Base Scripts -->
<script src="{% static 'js/vendor.js' %}" type="text/javascript"></script>
<script src="{% static 'js/app.js' %}" type="text/javascript"></script>
<script src="{% static 'js/main.js' %}" type="text/javascript"></script>
<script src="{% static 'sweetalert2/dist/sweetalert2.all.min.js' %}" type="text/javascript"></script>
<script src="{% static 'toastr/build/toastr.min.js' %}" type="text/javascript"></script>
<!-- Javascript custom -->
{% block scripts %}
{% endblock scripts %}
</body>
</html>

templates/base_alt.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>IQ' ERP | {% block head_title %} Bienvendio {% endblock %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
    <link href="{% static 'css/vendor.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/app-custom.css' %}" id="theme-style" rel="stylesheet" type="text/css">

    <script>
        var themeSettings = (localStorage.getItem('themeSettings')) ? JSON.parse(localStorage.getItem('themeSettings')) :
            {};
        var themeName = themeSettings.themeName || '';
        if (themeName)
        {
            document.write('<link rel="stylesheet" id="theme-style" href="/static/css/app-' + themeName + '.css">');
        }
        else
        {
            document.write('<link rel="stylesheet" id="theme-style" href="{% static 'css/app-custom.css' %}">');
        }
    </script>

    {% block styles %}
    {% endblock styles %}
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block head_scripts %}
    {% endblock head_scripts %}
</head>
<body>

{% block messages_container %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><i class="fa fa-times"></i></button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endblock messages_container %}
{% block content %}
{% endblock %}

<!-- Reference block for JS -->
<div class="ref" id="ref">
    <div class="color-primary"></div>
    <div class="chart">
        <div class="color-primary"></div>
        <div class="color-secondary"></div>
    </div>
</div>

<!-- Base Scripts -->
<script src="{% static 'js/vendor.js' %}" type="text/javascript"></script>
<script src="{% static 'js/app.js' %}" type="text/javascript"></script>
<script src="{% static 'js/main.js' %}" type="text/javascript"></script>
<!-- Javascript custom -->
{% block scripts %}
{% endblock scripts %}
</body>
</html>

templates/snippets/_form_default_buttons.html
<div class="text-right">
    {% if object.id %}
        <button type="submit" class="btn btn-warning">
            <i class="fa fa-pencil"></i> Editar
        </button>
    {% else %}
        <button type="submit" class="btn btn-success">
            <i class="fa fa-save"></i> Guardar
        </button>
    {% endif %}
    <a class="btn btn-secondary" href="{{ cancel_url }}">
        <i class="fa fa-times"></i> Cancelar
    </a>
</div>

templates/snippets/_form_modal_container.html
<div class="modal fade" id="form-modal" tabindex="-1" role="dialog" aria-labelledby="form-modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div id="form-modal-content" class="modal-content">
        </div>
    </div>
</div>

templates/snippets/_form_modal_content.html
{% load crispy_forms_tags %}

<form method="post" action="{{ action }}" autocomplete="off" novalidate>
    <div class="modal-header">
        <h5 class="modal-title">{{ title }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times</span>
        </button>
    </div>
    <div class="modal-body">
        {% include "snippets/_form_non_field_errors.html" %}
        {% crispy form %}
    </div>
    <div class="modal-footer">
        {% if object.id %}
            <button type="submit" class="btn btn-warning">
                <i class="fa fa-pencil"></i> Editar
            </button>
        {% else %}
            <button type="submit" class="btn btn-success">
                <i class="fa fa-save"></i> Guardar
            </button>
        {% endif %}
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
            <i class="fa fa-times"></i> Cancelar
        </button>
    </div>
</form>

templates/snippets/_form_non_field_errors.html
{% if form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <div class="m-alert__text">
            <strong>Error</strong><br>
            {{ form.non_field_errors }}
        </div>
        <div class="m-alert__close">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            </button>
        </div>
    </div>
{% endif %}

templates/snippets/_list_search_and_button.html
<!--begin: Search Form -->
<div class="row container-fluid">
    <div class="col-sm-12 col-md-5">
        <div class="input-group">
            <input id="search" type="text" class="form-control" placeholder="Buscar....." aria-label="Buscar">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fa fa-search"></i></span>
            </div>
        </div>
    </div>
    <div class="col-sm-12 offset-sm-0 col-md-5 offset-md-2 text-right">
        <button id="add-button" type="button" data-url="{{ create_url }}" class="btn btn-primary">
            <i class="fa fa-plus"></i> {{ button_text|default:"Nuevo" }}
        </button>
    </div>
</div>
<!--end: Search Form -->

templates/snippets/_list_search_and_link.html
<!--begin: Search Form -->
<div class="row container-fluid">
    <div class="col-sm-12 col-md-5">
        <div class="input-group">
            <input id="search" type="text" class="form-control" placeholder="Buscar....." aria-label="Buscar">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fa fa-search"></i></span>
            </div>
        </div>
    </div>
    <div class="col-sm-12 offset-sm-0 col-md-5 offset-md-2 text-right">
        <a id="add-link" href="{{ create_url }}" class="btn btn-primary">
            <i class="fa fa-plus"></i> {{ button_text|default:"Nuevo" }}
        </a>
    </div>
</div>
<!--end: Search Form -->